minimum_prek_version = "0.4.1"
default_install_hook_types = ["pre-commit", "pre-push"]
default_stages = ["pre-commit"]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "f12be1ebaa5351c1fc76472de98db2c3446c8253"  # frozen: v0.16.10
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "6972e4c5a7e9f45f05a2f30b668f221f43b770c9"  # frozen: v0.0.84
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml", args = ["--unsafe"] },
  { id = "check-toml" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-added-large-files" },
  { id = "detect-private-key" },
  { id = "fix-byte-order-marker" },
  { id = "no-commit-to-branch", args = ["--branch=main"] },
]
