minimum_prek_version = "0.4.1"
default_install_hook_types = ["pre-commit", "pre-push"]
default_stages = ["pre-commit"]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "2eeb5678de71a00c0902cbda7105d328432f72cb"  # frozen: v0.16.8
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "ac772f901bb576d192f2f219574a9f02194d51ed"  # frozen: v0.0.83
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml", args = ["--unsafe"] },
  { id = "check-toml" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-added-large-files" },
  { id = "detect-private-key" },
  { id = "fix-byte-order-marker" },
  { id = "no-commit-to-branch", args = ["--branch=main"] },
]
