name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    uses: IndrajeetPatil/workflows/.github/workflows/python-docs.yaml@0df2784483e1e8754f5e5d3b33f51cd25b665267
    permissions:
      contents: read
      pages: write
      id-token: write
