on:
  pull_request:
    branches: [main]

name: prek

jobs:
  prek:
    uses: IndrajeetPatil/workflows/.github/workflows/pre-commit.yaml@c73d24befb19ed51e2737558d076189ac23ad69d
    permissions:
      contents: read
