name: QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  qa:
    uses: IndrajeetPatil/workflows/.github/workflows/python-qa.yaml@310556bcfaedf6938b20971d9d81600f2d6ecf58 # python 3.15 toolchain (workflows #72)
