name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: IndrajeetPatil/workflows/.github/workflows/python-release.yaml@main
    permissions:
      contents: write
      id-token: write
