name: Package Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: IndrajeetPatil/workflows/.github/workflows/python-test.yaml@11355112cd25a795847bb93b6da964fa357f6978 # python 3.15 matrix (workflows #72)
