name: Package Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: IndrajeetPatil/workflows/.github/workflows/python-test.yaml@main
