name: Package Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: IndrajeetPatil/workflows/.github/workflows/python-test.yaml@4df5a32ed5b2026f39fe8347ae4ff1d45c79575a # python 3.15 matrix (workflows #72)
